# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'electchain' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for electchain

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  target 'electchainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
